//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aggregate_Crushing_Value_Test
    {
        public int ID { get; set; }
        public Nullable<int> Material_Description_ID { get; set; }
        public string Sample_No { get; set; }
        public string Size_Of_Aggregate { get; set; }
        public string Maximum_Load_Applied { get; set; }
        public string Duration_Of_Testing { get; set; }
        public string Weight_Of_Sample_Tested { get; set; }
        public string Weight_Of_Sample_Retained { get; set; }
        public string Aggregate_Crushing_Value { get; set; }
        public string Average_Agg_Crushing_Value { get; set; }
    
        public virtual Particle_Size_Distribution Particle_Size_Distribution { get; set; }
    }
}
