//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Density_Determination
    {
        public int ID { get; set; }
        public Nullable<int> Moisture_ID { get; set; }
        public string Soaking_Condition { get; set; }
        public string Model_Type { get; set; }
        public Nullable<int> Model_No { get; set; }
        public Nullable<decimal> Weight_Of_Soil_Plus_Mold { get; set; }
        public Nullable<decimal> Weight_Of_Mold { get; set; }
        public Nullable<decimal> Weight_Of_Soil { get; set; }
        public Nullable<decimal> Volume_Of_Mold { get; set; }
        public Nullable<decimal> Wet_Density_Of_Soil { get; set; }
        public Nullable<decimal> Dry_Density_Of_Soil { get; set; }
        public Nullable<int> Material_Description_ID { get; set; }
    
        public virtual Material_Description Material_Description { get; set; }
        public virtual Moisture Moisture { get; set; }
    }
}
