//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Density
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Density()
        {
            this.Moistures = new HashSet<Moisture>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Density_Trial_No { get; set; }
        public Nullable<decimal> Water_Added { get; set; }
        public Nullable<decimal> Weight_of_Soil_Plus_Mold { get; set; }
        public Nullable<decimal> Weight_of_Mold { get; set; }
        public Nullable<decimal> Weight_of_Soil { get; set; }
        public Nullable<decimal> Volume_of_Mold { get; set; }
        public Nullable<decimal> Wet_Density_of_Soil { get; set; }
        public Nullable<decimal> MDD { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Material_Description_ID { get; set; }
    
        public virtual Material_Description Material_Description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moisture> Moistures { get; set; }
    }
}
