//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Determination_OF_LL_PL
    {
        public int ID { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<int> Test_Number { get; set; }
        public string Container { get; set; }
        public string Determination_Type { get; set; }
        public string Test_Method { get; set; }
        public Nullable<decimal> Wt_of_Container_Plus_Wet_Soil { get; set; }
        public Nullable<decimal> Wt_of_Container_Plus_Dry_Soil { get; set; }
        public Nullable<decimal> Wt_of_Container { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
