//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Determnation_Of_Specific_Gravity_And_Water_Absorption_Of_Fine
    {
        public int ID { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<decimal> WSASDT { get; set; }
        public Nullable<decimal> WSSDAIA { get; set; }
        public Nullable<decimal> MoAIW { get; set; }
        public Nullable<decimal> Specific_Gravity { get; set; }
        public Nullable<decimal> Apparent_Specific_Gravity { get; set; }
        public Nullable<decimal> Water_Absorption_of_Aggregate { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
