//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Determination_Of_Flakiness_Index
    {
        public int ID { get; set; }
        public Nullable<int> Material_Description_ID { get; set; }
        public Nullable<decimal> Sieves_Nominal_Apperture_Size { get; set; }
        public Nullable<decimal> Mass_Of_Test_Portion { get; set; }
        public Nullable<decimal> Flakiness_Index { get; set; }
        public Nullable<decimal> Aggregate { get; set; }
        public Nullable<decimal> Flakiness_Index_Weighted_Average { get; set; }
        public Nullable<decimal> Total_Weight { get; set; }
    
        public virtual Material_Description Material_Description { get; set; }
    }
}
