//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Determnation_Of_Specific_Gravity_And_Water_Absorption_Of_Fine = new HashSet<Determnation_Of_Specific_Gravity_And_Water_Absorption_Of_Fine>();
            this.Determination_OF_LL_PL = new HashSet<Determination_OF_LL_PL>();
            this.Summary_Report = new HashSet<Summary_Report>();
        }
    
        public int ID { get; set; }
        public string Material_Description { get; set; }
        public string District { get; set; }
        public string Road_Section { get; set; }
        public string Quarry_Area { get; set; }
        public string Change { get; set; }
        public string Offset_Distance { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Elevation { get; set; }
        public string Estimated_Quantity { get; set; }
        public string Purpose { get; set; }
        public string Test_Result { get; set; }
        public Nullable<System.DateTime> Date_Sampled { get; set; }
        public Nullable<System.DateTime> Date_Tested { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Determnation_Of_Specific_Gravity_And_Water_Absorption_Of_Fine> Determnation_Of_Specific_Gravity_And_Water_Absorption_Of_Fine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Determination_OF_LL_PL> Determination_OF_LL_PL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Summary_Report> Summary_Report { get; set; }
    }
}
