//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Description
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material_Description()
        {
            this.Densities = new HashSet<Density>();
            this.Density_Determination = new HashSet<Density_Determination>();
            this.Moistures = new HashSet<Moisture>();
            this.Particle_Size_Distribution = new HashSet<Particle_Size_Distribution>();
            this.Particle_Size_Distribution1 = new HashSet<Particle_Size_Distribution>();
            this.Penetration_Test_Data = new HashSet<Penetration_Test_Data>();
            this.Moisture_Determination = new HashSet<Moisture_Determination>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Tester_ID { get; set; }
        public string Project_Name { get; set; }
        public string Material_Description1 { get; set; }
        public string Purpose { get; set; }
        public string Chainage { get; set; }
        public string Tested_At { get; set; }
        public string Sample_Taken_From { get; set; }
        public string Date_Sampled { get; set; }
        public string Date_Tested { get; set; }
        public string Sample_No { get; set; }
        public string Determination { get; set; }
        public Nullable<int> Number_of_Blows { get; set; }
        public Nullable<int> Determination_No { get; set; }
        public string Container { get; set; }
        public Nullable<decimal> Wt_Of_Container_Plus_Wet_Soil { get; set; }
        public Nullable<decimal> Wt_Of_Container_Plus_Dry_Soil { get; set; }
        public Nullable<decimal> Wt_Of_Container { get; set; }
        public Nullable<decimal> Wt_Of_Water { get; set; }
        public Nullable<decimal> Wt_Of_Dry_Soil { get; set; }
        public Nullable<decimal> Moisture_Container { get; set; }
        public Nullable<decimal> Average { get; set; }
        public string Soil_Classification { get; set; }
        public Nullable<decimal> Liquid_Limit_Average { get; set; }
        public Nullable<decimal> Plastic_Limit_Average { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Density> Densities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Density_Determination> Density_Determination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moisture> Moistures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Particle_Size_Distribution> Particle_Size_Distribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Particle_Size_Distribution> Particle_Size_Distribution1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penetration_Test_Data> Penetration_Test_Data { get; set; }
        public virtual Determination_Of_Flakiness_Index Determination_Of_Flakiness_Index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moisture_Determination> Moisture_Determination { get; set; }
    }
}
