//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Particle_Size_Distribution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Particle_Size_Distribution()
        {
            this.Aggregate_Crushing_Value_Test = new HashSet<Aggregate_Crushing_Value_Test>();
        }
    
        public int ID { get; set; }
        public string Sample_Preparation { get; set; }
        public string Method_Of_Sieving { get; set; }
        public Nullable<decimal> Sieve_Size { get; set; }
        public Nullable<decimal> Weight_Retained { get; set; }
        public Nullable<decimal> Retained_Percent { get; set; }
        public Nullable<decimal> Passing_Percent { get; set; }
        public string Note { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Material_Description_ID { get; set; }
    
        public virtual Material_Description Material_Description { get; set; }
        public virtual Material_Description Material_Description1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aggregate_Crushing_Value_Test> Aggregate_Crushing_Value_Test { get; set; }
    }
}
