//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary_Report
    {
        public int ID { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public string Quarry_Area { get; set; }
        public string Chanage { get; set; }
        public string Offset_Distance { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longtiude { get; set; }
        public string Eatimated_Quantiy { get; set; }
        public Nullable<decimal> LL { get; set; }
        public string PI { get; set; }
        public string SC { get; set; }
        public Nullable<decimal> PP { get; set; }
        public Nullable<decimal> GM { get; set; }
        public Nullable<decimal> PM { get; set; }
        public string OMC { get; set; }
        public string MDD { get; set; }
        public string CBR { get; set; }
        public string SWELL { get; set; }
        public Nullable<decimal> ACV { get; set; }
        public Nullable<decimal> TFV { get; set; }
        public Nullable<decimal> LAA { get; set; }
        public Nullable<decimal> FI { get; set; }
        public Nullable<decimal> SGR { get; set; }
        public Nullable<decimal> WAT { get; set; }
        public Nullable<decimal> ST { get; set; }
        public Nullable<decimal> SEVT { get; set; }
        public string Purpose_of_Material { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
