//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ten_Percent_Fines_Value
    {
        public int ID { get; set; }
        public Nullable<int> Sample_No { get; set; }
        public Nullable<decimal> Size_OF_Aggregate { get; set; }
        public Nullable<decimal> Load_Achived { get; set; }
        public string Duration_Of_Testing { get; set; }
        public Nullable<decimal> Penetration_Of_Plunger { get; set; }
        public Nullable<decimal> Weight_Of_Sample_Tested { get; set; }
        public Nullable<decimal> Weight_Of_Sample_Retained { get; set; }
        public Nullable<decimal> Material_Passing { get; set; }
        public Nullable<decimal> Force_Required_To_Produce { get; set; }
        public Nullable<decimal> Average_Force { get; set; }
        public Nullable<decimal> Wet { get; set; }
        public string Remark { get; set; }
    }
}
